// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface GanttStoryblok {
  tasks?: (GanttStoryblok | HeaderStoryblok | PageStoryblok | TaskStoryblok)[];
  component: "gantt";
  _uid: string;
  [k: string]: any;
}

export interface HeaderStoryblok {
  title?: string;
  component: "header";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (GanttStoryblok | HeaderStoryblok | PageStoryblok | TaskStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TaskStoryblok {
  id?: string;
  name?: string;
  percentDone?: string;
  startDate?: string;
  endDate?: string;
  manuallyScheduled?: boolean;
  effort?: string;
  draggable?: boolean;
  resizable?: boolean;
  component: "task";
  _uid: string;
  [k: string]: any;
}
